Hello:
	javac $@.java
	java $@

Beer:
	javac $@.java
	java $@

PhraseBuilder:
	javac $@.java
	java $@
puzzle:
	javac $@.java
	java $@

App:
	javac $@.java
	java $@
TestArrays:
	javac $@.java
	java $@
Triangle:
	javac $@.java
	java $@
