drop table if exists fias_addrobj;
create table fias_addrobj (
    actstatus integer,
    aoguid varchar(36),
    aoid varchar(36),
    aolevel bigint,
    areacode varchar(3),
    autocode varchar(1),
    cadnum varchar(100),
    centstatus bigint,
    citycode varchar(3),
    code varchar(17),
    ctarcode varchar(3),
    currstatus bigint,
    divtype integer,
    enddate timestamp,
    extrcode varchar(4),
    formalname varchar(120),
    ifnsfl varchar(4),
    ifnsul varchar(4),
    livestatus integer,
    nextid varchar(36),
    normdoc varchar(36),
    offname varchar(120),
    okato varchar(11),
    oktmo varchar(11),
    operstatus bigint,
    parentguid varchar(36),
    placecode varchar(3),
    plaincode varchar(15),
    plancode varchar(4),
    postalcode varchar(6),
    previd varchar(36),
    regioncode varchar(2),
    sextcode varchar(3),
    shortname varchar(10),
    startdate timestamp,
    streetcode varchar(4),
    terrifnsfl varchar(4),
    terrifnsul varchar(4),
    updatedate timestamp,

    primary key (aoid)
)
