tasks:
	php tasks.php
hello:
	php hello.php
phone:
	php phone.php
phonebd:
	mysql -u test -p phonebook < phone.sql
urldb:
	psql -h localhost -d urls -U test -f urls.sql
urls:
	php urls.php
deploy:
	sudo ./deploy.sh
dbtest1:
	psql -h localhost -d urls -U test -f dbtest1.sql
db1:
	psql -h localhost -d urls -U test -f db1.sql

socium:
	php socium.php
